version: '3.8'

services:
  app:
    build: .  # This tells Docker to build using the Dockerfile in current directory
    image: product:crush-backend  # Match the name in your screenshot
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/productdb
      - SPRING_DATASOURCE_USERNAME=assiyad
      - SPRING_DATASOURCE_PASSWORD=password

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=assiyad
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=productdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U assiyad -d productdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: